spring:
  cloud:
    gateway:
      server:
        webflux:
          httpclient:
            connect-timeout: 3000
            response-timeout: 8s

minibanking:
  gateway:
    configuration-source: config-server
  security:
    client-id: minibanking-cli
